### ISSUE TITLE
[BUG] ph5availability is inconsistent with stored time series data 

### ISSUE THREAD

**Issue by timronan** [PIC-IRIS/PH5#416]
**Describe the bug**
the ph5availabilty function outputs a result that is inconsistent with the timeseries data stored in a ph5expirment. 

**Environment (please complete the following information):**
 - Centos 7
 - Program Version [ph5toms 2018.268]
 - Version: 2019.101 ph5availability

**To Reproduce**
Track the time series data using ph5toms. Add a print statement to line 215 in ph5toms 
print(s)

Run ph5toms over a timespan of interest and save the printed output. 
Compare this output to the availability results from the same SNCL and timespan. Gaps are not appearing in the ph5availabilty result. 

**Expected behavior**
ph5availabilty should show the same gaps that are output by  s = stream.traces[0].stats. s = stream.traces[0].stats is a ground truth for the time series data stored in a ph5 file and the availability should accurately reflect the stored time series data. 

**Screenshots**

printout of traace stats in ph5toms

``` 
       network: XD
         station: MA05
        location: 
         channel: HHZ
       starttime: 2014-06-25T00:00:00.005000Z
         endtime: 2014-06-25T11:59:59.995000Z
   sampling_rate: 100.0
           delta: 0.01
            npts: 4320000
           calib: 1.0
     coordinates: AttribDict({'latitude': 46.754669, 'longitude': -122.226189})
```
```
ph5availability -n master.ph5 -p ./ -s 2014-06-24T00:00:00 -e 2014-06-26T23:25:59 --station  MA05 --channel HHZ -a 2
#n s      l  c   q                    earliest                      latest
XD MA05   -- HHZ   2014-06-24T00:00:00.000000Z 2014-06-26T23:25:59.000000Z
```

PH5availability should print out multiple lines showing these data gaps. 

**Additional context**
